name: Lee Worden research prototype website
markdown: kramdown
highlighter: true
description: "Lee Worden prototype research website"
#url: "jekyll-new.joelglovier.com"
permalink: /posts/:title
exclude: wmd_files/SageDynamicsRepo/.git
