# This file was *autogenerated* from the file popdyn-example.sage
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_10 = Integer(10); _sage_const_15 = Integer(15)# requires: $(SageDynamics)/dynamicalsystems.py
# requires: $(SageUtils)/latex_output.py
# produces: popdyn-example.cd.tex popdyn-example.svg
from sage.all import * 
from sage.misc.latex import _latex_file_
 
sys.path.append( os.environ['SageUtils'] )
sys.path.append( os.environ['SageDynamics'] )
import dynamicalsystems
import latex_output

ltx = latex_output.latex_output( 'popdyn-example.cd.tex' )

# now that I've defined the general resource-competition model, let's
# create a 1-resource, 1-population instantiation to work with
var('X_1 X_2')
sys = dynamicalsystems.ODESystem(
	{ X_1: X_1 - _sage_const_1 /_sage_const_5 *X_1**_sage_const_2  - _sage_const_1 /_sage_const_10 *X_1*X_2, X_2: X_2 - _sage_const_1 /_sage_const_5 *X_1*X_2 - _sage_const_1 /_sage_const_3 *X_2**_sage_const_2  },
	[ X_1, X_2 ]
)

ltx.write( sys )

soln = sys.solve( [ _sage_const_1 , _sage_const_9  ], end_time=_sage_const_15  )
ts = Graphics()
ts += soln.plot( 't', X_1, color='red', legend_label='$X_1$' )
ts += soln.plot( 't', X_2, color='blue', legend_label='$X_2$' )
ts.set_legend_options( back_color='white' )
ts.axes_labels( [ "$t$", "$X$" ] )
ts.save( 'popdyn-example.svg', figsize=(_sage_const_4 ,_sage_const_3 ) )

save_session('popdyn-example')

ltx.close()
#save_session('foodweb')
#sys.exit( 0r )
