# This file was *autogenerated* from the file SI.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5)# requires: $(SageDynamics)/dynamicalsystems.py
# requires: $(SageUtils)/latex_output.py
# produces: SI.sobj SI.sage.out.tex SI.png
from sage.all import * 
from sage.misc.latex import _latex_file_
 
sys.path.append( os.environ['SageUtils'] )
sys.path.append( os.environ['SageDynamics'] )

import latex_output
import dynamicalsystems

ltx = latex_output.latex_output( 'SI.sage.out.tex' )

# now that I've defined the general resource-competition model, let's
# create a 1-resource, 1-population instantiation to work with
var('S I r')
SI = dynamicalsystems.ODESystem(
	{ S: - r*S*I, I: r*S*I },
	[S, I],
	bindings = dynamicalsystems.Bindings( { 'r':_sage_const_1  } )
)

ltx.write( 'The SI model:' )
ltx.write_block( SI )

SI_phase_plane = SI.plot_vector_field( (I,_sage_const_0 ,_sage_const_2 ), (S,_sage_const_0 ,_sage_const_2 ), color='gray' )

#ltx.close()
#save_session('foodweb')
#sys.exit( 0r )

equil = SI.equilibria()
ltx.write( 'equilibria: ', latex(equil) )

SI_phase_plane.save( 'SI.png', figsize=(_sage_const_5 ,_sage_const_5 ) )

ltx.close()

save_session('SI')
