# This file was *autogenerated* from the file aij-assemble.sage
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_0 = Integer(0)# requires: aij.py
# requires: $(SageDynamics)/dynamicalsystems.py
# requires: $(SageUtils)/latex_output.py
# produces: aij-assemble.sobj
from sage.all import *
from sage.misc.latex import _latex_file_

import aij
import latex_output
import dynamicalsystems

set_random_seed(_sage_const_0 )

comm2 = aij.AijModel( _sage_const_1  )

save_session( 'aij-assemble' )
