# This file was *autogenerated* from the file direct-assemble.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)# requires: direct.py
# produces: direct-assemble.sobj
from sage.all import *
from sage.misc.latex import _latex_file_

import direct
import dynamicalsystems

set_random_seed(_sage_const_0 )

N_pop = _sage_const_1 #5

comm2 = direct.DirectModel( _sage_const_2  )

save_session( 'direct-assemble' )
