# This file was *autogenerated* from the file foodweb-2-2.sage
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_9 = Integer(9); _sage_const_0p1 = RealNumber('0.1'); _sage_const_10 = Integer(10); _sage_const_0p02 = RealNumber('0.02'); _sage_const_30 = Integer(30); _sage_const_0p07 = RealNumber('0.07')# requires: foodweb.py
# requires: $(SageDynamics)/dynamicalsystems.py
# requires: $(SageAdaptiveDynamics)/adaptivedynamics.py
# requires: $(SageUtils)/latex_output.py
# produces: foodweb-2-2.sobj foodweb-2-2.sage.out.tex foodweb-2-2.tikz.tex
from sage.all import * 
from sage.misc.latex import _latex_file_

import foodweb
import latex_output
import dynamicalsystems
import adaptivedynamics
import lotkavolterra

ltx = latex_output.latex_output( 'foodweb-2-2.sage.out.tex' )

# now that I've defined the general resource-competition model, let's
# create a 1-resource, 1-population instantiation to work with
var('R_0 R_1 P_0 P_1')
foodweb_2_2 = foodweb.FoodWebModel(
    DiGraph( { R_0:[P_0,P_1], R_1:[P_0,P_1] } ),
    bindings = dynamicalsystems.Bindings( { 'r':_sage_const_1 , 'm':_sage_const_1  } )
);

fb = ( dynamicalsystems.FunctionBindings( { 'f':SR('1 + cos( u - v )').function(SR('u'),SR('v')) } )
    + dynamicalsystems.Bindings( k=_sage_const_9 /_sage_const_10  ) )

fb_2_2 = foodweb_2_2.bind(fb)

ltx.write( 'The foodweb model:', fb_2_2 )

foodweb_2_2.plot_tikz( 'foodweb-2-2.tikz.tex' )

#ltx.close()
#save_session('foodweb-2-2')
#sys.exit( 0r )

equil = fb_2_2.interior_equilibria()
print equil

init_2_2 = dynamicalsystems.Bindings( { 'u_0_R_0':-_sage_const_0p1 , 'u_0_R_1':_sage_const_0 , 'u_0_P_0':-_sage_const_0p07 , 'u_0_P_1':_sage_const_0p02  } ) 

#print init_2_2( dynamicalsystems.Bindings( equil[0] ) )

foodweb_adap = adaptivedynamics.AdaptiveDynamicsModel( 
    foodweb_2_2,
    [ foodweb_2_2._u_indexer ],
    equilibrium = dynamicalsystems.Bindings()
    #equilibrium = dynamicalsystems.Bindings( equil[0] )
).bind( { 'gamma':_sage_const_1  } )

ltx.write( 'Adaptive dynamics of model:\n', foodweb_adap )

#ltx.write_environment( 'align*', [ '\\\\\n  '.join( r'\frac{d%s}{dt} &\propto %s' % (latex(v), latex(foodweb_adap._S[v])) for v in foodweb_adap._vars ) ] )

#ltx.write( 'flow at ', '$%s$'%latex( latex_output.column_vector( [ init_2_2( v ) for v in foodweb_adap._vars ] ) ), ': ',
#    '$%s$'%latex( latex_output.column_vector( init_2_2( foodweb_adap._flow[v] ) for v in foodweb_adap._vars ) ) )

fb_adap = foodweb_adap.bind( fb + dynamicalsystems.Bindings( equil[_sage_const_0 ] ) )

#ltx.write( 'Bound adaptive dynamics:\n', fb_adap )

traj_2_2 = fb_adap.solve( [ init_2_2( v ) for v in foodweb_adap._vars ], end_time=_sage_const_30  ) #, step=0.003 )

print traj_2_2._timeseries

ltx.close()

save_session('foodweb-2-2')
