# This file was *autogenerated* from the file foodweb2.sage
from sage.all_cmdline import *   # import sage library
_sage_const_9 = Integer(9); _sage_const_10 = Integer(10); _sage_const_1 = Integer(1); _sage_const_50 = Integer(50)# requires: foodweb2.py
# produces: foodweb2.sobj foodweb2.sage.out.tex foodweb2.tikz.tex
from sage.all import * 

import foodweb2
import dynamicalsystems

ltx = dynamicalsystems.latex_output( 'foodweb2.sage.out.tex' )

# now that I've defined the general resource-competition model, let's
# create a 1-resource, 1-population instantiation to work with
var('a b')

fb = (
    dynamicalsystems.Bindings( k = _sage_const_9 /_sage_const_10 , slow=_sage_const_1 /_sage_const_50  ) +
    dynamicalsystems.FunctionBindings( { 'f':SR('2 + 4/5*cos( u - v )').function(SR('u'),SR('v')) } )
)

foodweb_pred_prey = foodweb2.FoodWebModel(
    DiGraph( { a:[b] } ),
    bindings = dynamicalsystems.Bindings( { 'r':_sage_const_1 , 'm':_sage_const_1  } )
);

ltx.write( 'The foodweb model:', foodweb_pred_prey.bind(fb) )

foodweb_pred_prey.plot_tikz( 'foodweb2.tikz.tex' )

ltx.close()
save_session('foodweb2')
#sys.exit( 0r )
