# This file was *autogenerated* from the file foodweb.plot.sage
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_1p9945 = RealNumber('1.9945'); _sage_const_100 = Integer(100); _sage_const_1p796 = RealNumber('1.796'); _sage_const_500 = Integer(500); _sage_const_1p795 = RealNumber('1.795'); _sage_const_1p9955 = RealNumber('1.9955'); _sage_const_3p2 = RealNumber('3.2')# requires: foodweb-adap.sobj
# produces: foodweb.plot.sage.out.tex 
# produces: foodweb-pred-prey-adap.png foodweb-pred-prey-adap.svg
# produces: foodweb-pred-prey-adap-difference.png
# produces: foodweb-pred-prey-a-vs-t.png foodweb-pred-prey-a-vs-a.png
# produces: foodweb-pred-prey-x-vs-t.png
from sage.all import *
from sage.misc.latex import _latex_file_
from sage.misc.latex import latex

import foodweb
import dynamicalsystems
import lotkavolterra

# create variables with custom latex names because load_session
# creates them wrong: http://trac.sagemath.org/ticket/17559
#for x in ('X_0', 'X_i', 'R_0'): hat(SR.symbol(x))
#SR.symbol( 'c_0_0', latex_name='c_{00}' )
#SR.symbol( 'c_i_0', latex_name='c_{i0}' )

load_session("foodweb-adap")

ltx = dynamicalsystems.latex_output( 'foodweb.plot.sage.out.tex' )

#foodweb_adap.bind_in_place( fb )

print 'flow at initial conditions:', pred_prey_init( foodweb_adap._flow )

ppp = Graphics()
for v, c, l in zip( foodweb_adap._vars, ['blue', 'red'], ['prey $u_0$','predator $u_1$'] ):
    ppp += pred_prey_traj.plot( 't', v, color=c, legend_label=l )
ppp.save( 'foodweb-pred-prey-adap.png',
    ticks=[_sage_const_100 ,pi],
    tick_formatter=[None,pi],
    figsize=(_sage_const_5 ,_sage_const_5 )
)
ppp.save( 'foodweb-pred-prey-adap.svg',
    ticks=[_sage_const_500 ,pi],
    tick_formatter=[None,pi],
    figsize=(_sage_const_3 ,_sage_const_3 )
)

pred_prey_traj.plot( 't', 'u_0_a - u_0_b', legend_label='$u_0-u_1$' ).save(
    'foodweb-pred-prey-adap-difference.png',
    ymin=_sage_const_0 ,
    ymax=_sage_const_3p2 ,
    ticks=[_sage_const_100 ,pi/_sage_const_2 ],
    tick_formatter=[None,pi],
    figsize=(_sage_const_5 ,_sage_const_5 )
)

xs = foodweb_adap._popdyn_model.equilibrium_vars()
ppx = Graphics()
for xhat in xs:
    ppx += pred_prey_traj.plot( 't', xhat, legend_label='$%s$'%latex(xhat) )
ppx.save( 'foodweb-pred-prey-x-vs-t.png', figsize=(_sage_const_5 ,_sage_const_5 ) )

flv = lotkavolterra.LotkaVolterraAdaptiveDynamics( foodweb_adap,
	r_name_indexer=foodweb.vertex_indexer('r'),
        a_name_indexer=foodweb.vertex_indexer_2d('a') )

atp = Graphics()
for i in foodweb_adap._popdyn_model._population_indices:
    for j in foodweb_adap._popdyn_model._population_indices:
	atp += pred_prey_traj.plot( 't', fb( flv._lv_model._A_bindings( flv._lv_model._a_indexer[i][j] ) ),
	    color = (i == j and 'red' or 'green') )
atp.save( 'foodweb-pred-prey-a-vs-t.png', figsize=(_sage_const_5 ,_sage_const_5 ) )

lotkavolterra.plot_aij_with_arrows( pred_prey_traj, flv, 'foodweb-pred-prey-a-vs-a.png', bindings=fb )

lotkavolterra.plot_aij_with_arrows( pred_prey_traj, flv, 'foodweb-pred-prey-a-vs-a-detail.png', bindings=fb, xmin=-_sage_const_1p9955 , xmax=-_sage_const_1p9945 , ymin=_sage_const_1p795 , ymax=_sage_const_1p796  )

ltx.close()
