# This file was *autogenerated* from the file foodweb2-adap-traj.sage
from sage.all_cmdline import *   # import sage library
_sage_const_0p1 = RealNumber('0.1'); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_1000 = Integer(1000)# requires: foodweb2-adap.sobj
# produces: foodweb2-adap-traj.sobj
from sage.all import *

import foodweb2, dynamicalsystems, lotkavolterra

load_session("foodweb2-adap")

pred_prey_init = dynamicalsystems.Bindings( { 'u_a_0':_sage_const_0p1 , 'u_b_0':_sage_const_0 , 'gamma_a_0':_sage_const_0 , 'gamma_b_0':_sage_const_0 , 'sigma_a_0':_sage_const_1 , 'sigma_b_0':_sage_const_1  } )

#ltx.write( 'flow at ', '$%s$'%latex( dynamicalsystems.column_vector( [ pred_prey_init( v ) for v in foodweb_adap._vars ] ) ), ': ', 
#    '$%s$'%latex( dynamicalsystems.column_vector( pred_prey_init( foodweb_adap._flow[v] ) for v in foodweb_adap._vars ) ) )

pred_prey_traj = foodweb_adap.solve( [ pred_prey_init( v ) for v in foodweb_adap._vars ], end_time=_sage_const_1000  ) #, step=0.003 )

save_session('foodweb2-adap-traj')
