# This file was *autogenerated* from the file logistic-S-A-curve.sage
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5)# requires: S-A-vf.sobj
# produces: logistic-S-A-curve.png
import os, sys
sys.path.append( os.environ['SageUtils'] )
sys.path.append( os.environ['SageDynamics'] )
sys.path.append( os.environ['SageAdaptiveDynamics'] )
from dynamicalsystems import *
from adaptivedynamics import *
from plot_vector_field_along_curve import *
from sage.symbolic.function_factory import function

load_session( 'S-A-vf.sobj' )
var( 'a k u' )
r = function('r', u)
K = function('K', u)
verhulst_AK_bindings = Bindings( k=r, a=-r/K )
verhulst_curve_form = verhulst_AK_bindings( vector( [k, a] ) )
verhulst_d1a_form = diff( verhulst_curve_form, u ) #vector( [ diff(r), diff(-r/K) ] )
verhulst_d1a_vf = verhulst_d1a_form * sign(verhulst_d1a_form*verhulst_AK_bindings(SA)) / verhulst_d1a_form.norm(_sage_const_2 )

def plot_v_curve( bindings, urange ):
    return (
	plot( bindings(verhulst_curve_form), urange, color='black', parametric=True ) + 
	plot_vector_field_on_curve( bindings(verhulst_d1a_vf), bindings(verhulst_curve_form), urange, color='blue', frame=False )
    )

verhulst_SA = SAvf
verhulst_SA += plot_v_curve( FunctionBindings( r=SR(_sage_const_1 ), K=u ), (u,_sage_const_1 /_sage_const_3 ,_sage_const_5 ) )
verhulst_SA += plot_v_curve( FunctionBindings( r=u, K=u ), (u,_sage_const_0 ,_sage_const_3 ) )
verhulst_SA += plot_v_curve( FunctionBindings( r=_sage_const_1 /u+_sage_const_1 , K=u ), (u,_sage_const_1 /sqrt(_sage_const_3 ),_sage_const_3 ) )
verhulst_SA += plot_v_curve( FunctionBindings( r=_sage_const_1 /u, K=u ), (u,_sage_const_1 /sqrt(_sage_const_3 ),_sage_const_3 ) )

# pity about the labels
# wouldn't want anything to happen to them
verhulst_SA.axes_labels( [ '$k$', '$a$' ] );
verhulst_SA.save( 'logistic-S-A-curve.png', figsize=(_sage_const_5 ,_sage_const_5 ) )
