# This file was *autogenerated* from the file maclev-2-2-c-p.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_4 = Integer(4)# requires: maclevmodels.py
# requires: maclev_2_2_defs.py maclev-2-2-c-adap.sobj
# produces: maclev-2-2-c-p.sage.out.tex maclev-2-2-c-c-vs-c.png
# produces: maclev-2-2-c-c-vs-t.png maclev-2-2-c-R-vs-t.png
# produces: maclev-2-2-c-c-vs-t.svg maclev-2-2-c-R-vs-t.svg
from maclev_2_2_defs import *

load_session( 'maclev-2-2-c-adap' )

ltx = latex_output( 'maclev-2-2-c-p.sage.out.tex' )

# plot c_1 vs c_0, with arrows

print 'plot c vs c'
sys.stdout.flush()

# first put in the curves in the c_0-c_1 plane
c_phase_plane = Graphics()
for i in maclev._population_indices:
    ci = [ rescomp._indexers['c'][i][_sage_const_0 ], rescomp._indexers['c'][i][_sage_const_1 ] ]
    c_phase_plane += c_evolution.plot( ci[_sage_const_0 ], ci[_sage_const_1 ], color=[ 'blue', 'red' ][i] )

c_phase_plane.axes_labels( [ '$c_0$', '$c_1$' ] )
c_phase_plane.save( 'maclev-2-2-c-c-vs-c.png', figsize=(_sage_const_6 ,_sage_const_6 ), xmin=_sage_const_0 , ymin=_sage_const_0  )

c_timeseries = Graphics()
colors = rainbow( len(maclev._population_indices) * len(rescomp._r_indices) )
for i in maclev._population_indices:
    for l in rescomp._r_indices:
	c_timeseries += c_evolution.plot( 't', rescomp._indexers['c'][i][l],
	   color=colors.pop(), legend_label='$c_{%d%d}$'%(i+_sage_const_1 ,l+_sage_const_1 ) )
c_timeseries.save( 'maclev-2-2-c-c-vs-t.png', figsize=(_sage_const_4 ,_sage_const_4 ), ymin=_sage_const_0  )
c_timeseries.save( 'maclev-2-2-c-c-vs-t.svg', figsize=(_sage_const_2 ,_sage_const_2 ), ymin=_sage_const_0  )

r_timeseries = Graphics()
colors = ['blue','red']
for l in rescomp._r_indices:
    r_timeseries += c_evolution.plot( 't',
	maclev._bindings( rescomp.add_hats()( rescomp._indexers['R'][l] ) ),
	color=colors.pop(),
	legend_label=latex( rescomp.add_hats()( rescomp._indexers['R'][l+_sage_const_1 ] ) ) )
r_timeseries.axes_labels( [ '$t$', '$\hat R$' ] )
r_timeseries.save( 'maclev-2-2-c-R-vs-t.png', figsize=(_sage_const_4 ,_sage_const_4 ), ymin=_sage_const_0  )
r_timeseries.save( 'maclev-2-2-c-R-vs-t.svg', figsize=(_sage_const_2 ,_sage_const_2 ), ymin=_sage_const_0  )

ltx.close()
save_session( 'maclev-2-2-c-p' )
