# This file was *autogenerated* from the file maclev-2-2-a-c-popdyn.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_0p02 = RealNumber('0.02'); _sage_const_0p05 = RealNumber('0.05')# requires: maclev_a_c.py maclev_2_2_defs.py maclevmodels.py
# produces: maclev-2-2-a-c-popdyn.sage.out.tex maclev-2-2-a-c-popdyn.sobj
# produces: maclev-2-2-a-c-popdyn.png maclev-2-2-a-c-r-zngis.png
from maclev_a_c import *

print 'start'
sys.stdout.flush()

ltx = latex_output( 'maclev-2-2-a-c-popdyn.sage.out.tex' )

ltx.write( 'The Mac-Lev model in generic form: ' )
ltx.write_block( maclev )

#print 'apply bindings:', ad_bindings
#sys.stdout.flush()

ltx.write( 'The Mac-Lev model with $c$ varying freely:' )
ltx.write_block( maclev.bind( ad_bindings + numeric_params ) )

print 'plot state space'
sys.stdout.flush()

maclev_initial_system = maclev.bind( ad_bindings + numeric_params + initial_conditions )
#ltx.write( 'Initial system bindings:', ad_bindings + numeric_params + initial_conditions )
#ltx.write( 'Initial system:', maclev_initial_system )

p = maclev_initial_system.plot_vector_field( (X_0, _sage_const_0 , _sage_const_2 ), (X_1, _sage_const_0 , _sage_const_2 ), color="gray", figsize=(_sage_const_5 ,_sage_const_5 ) )
p += maclev_initial_system.plot_ZNGIs( (X_0, _sage_const_0 , _sage_const_2 ), (X_1, _sage_const_0 , _sage_const_2 ), color="gray" )
s = maclev_initial_system.solve( [_sage_const_0p02 , _sage_const_0p05 ], end_time=integrate_popdyn_to )
p += s.plot( X_0, X_1, color='red' )
p.save( 'maclev-2-2-a-c-popdyn.png' )

rescomp_initial_system = maclev._rescomp_model.bind( ad_bindings + numeric_params + initial_conditions )
rescomp_initial_system.plot_R_ZNGIs( filename='maclev-2-2-a-c-r-zngis.png', figsize=(_sage_const_4 ,_sage_const_4 ), ymin=_sage_const_0 , ymax=_sage_const_4 , xmin=_sage_const_0 , xmax=_sage_const_4  )

ltx.close()

save_session('maclev-2-2-a-c-popdyn')
