# This file was *autogenerated* from the file masel-2.sage
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1)# requires: masel_model.py
# produces: masel-model.tex
from sage.all import *
import os, sys
sys.path.append( os.environ['SageDynamicsRepo'] )
import masel_model
from latex_output import latex_output

ltx = latex_output( 'masel-model.tex' )
ltx.write( masel_model.MaselModel(_sage_const_1 ) )
ltx.close()
