# This file was *autogenerated* from the file S-A-vector-field.sage
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4)# produces: S-A-vector-field.png
var( 'a k' );
outer = _sage_const_3 
SAvf = plot_vector_field( [-a/k, _sage_const_1 ], [a,-outer,_sage_const_0 ], [k,_sage_const_0 ,outer], color='red', figsize=(_sage_const_4 ,_sage_const_4 ), frame=false );
SAvf.axes_labels( [ '$a$', '$k$' ] );
SAvf.save( 'S-A-vector-field.png' );
